create table tb_curves (id int8 generated by default as identity, name varchar(255), primary key (id));
create table tb_pairs (id int8 generated by default as identity, first varchar(255), second varchar(255), curve_id int8, primary key (id));
alter table if exists tb_pairs add constraint FKi5jacg0b32lx79sue0wrv7bky foreign key (curve_id) references tb_curves;
